__title__ = "pbipy"
__description__ = "A Power BI Rest API wrapper for Python."
__url__ = "https://github.com/andrewvillazon/pbipy"
__version__ = "2.0.0-alpha"
__author__ = "Andrew Villazon"
__author_email__ = "andrew.villazon@gmail.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2023 Andrew Villazon"